/**
 * This file is part of Caraxes
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

using System.Text;
using YamlDotNet.Serialization;

namespace Caraxes.Core.Cluster;

/// <summary>
/// Generates the docker compose file for a cluster plan. One prebuilt image for every node
/// (identity is runtime environment, not build args), static IPs on a dedicated /24 (the raft
/// TLS cert SANs are IP-based), named volumes, and NET_ADMIN so fault injection can drive
/// tc/iptables inside the containers. <c>restart: no</c> is deliberate: a nemesis kill must stay
/// killed until the scenario says otherwise.
/// </summary>
public static class ComposeGenerator
{
    /// <param name="configDirInCompose">Path of the generated per-node config directory as
    /// referenced from the compose file (relative paths resolve against the compose file's own
    /// directory).</param>
    /// <remarks>
    /// The TLS certificate is deliberately NOT mounted: the image bakes the .pfx and its CA
    /// anchor together at build time, and <c>up</c> couples cert regeneration to an image
    /// rebuild, so the pair is consistent by construction. A single-file bind mount of the .pfx
    /// was observed serving a STALE previous-generation file on Docker Desktop (the mount pins
    /// content across host-side file replacement), which broke inter-node TLS with UntrustedRoot
    /// while every on-disk artifact looked correct.
    /// </remarks>
    public static string Generate(ClusterPlan plan, string configDirInCompose)
    {
        ClusterSpec spec = plan.Spec;

        Dictionary<string, object> services = [];
        Dictionary<string, object> volumes = [];

        foreach (NodePlan node in plan.Nodes)
        {
            services[node.Name] = new Dictionary<string, object>
            {
                ["image"] = spec.EffectiveImage,
                ["container_name"] = node.ContainerName,
                ["restart"] = "no",
                ["cap_add"] = new List<string> { "NET_ADMIN" },
                ["environment"] = new Dictionary<string, object>
                {
                    ["CAMUS_RAFT_NODENAME"] = node.Name,
                    ["CAMUS_RAFT_NODEID"] = node.Index,
                    ["CAMUS_RAFT_HOST"] = node.Ip,
                    ["CAMUS_RAFT_PORT"] = node.RaftPort,
                    ["CAMUS_HTTP_PORT"] = 5095,
                    ["CAMUS_INITIAL_CLUSTER"] = node.InitialCluster,
                    ["CAMUS_INITIAL_CLUSTER_PARTITIONS"] = spec.Partitions,
                    // CamusDB's config discovery honors CAMUS_CONFIG_PATH ahead of the image's
                    // baked ./Config/config.yml, and CLI flags still outrank the file for identity.
                    ["CAMUS_CONFIG_PATH"] = $"/app/caraxes-config/{node.Name}.yml",
                },
                ["ports"] = new List<string>
                {
                    $"{node.HostRestPort}:5095",
                    $"{node.HostGrpcPort}:5096",
                },
                // The config is a DIRECTORY mount on purpose: a single-file bind mount pins the
                // file's content across host-side regeneration (same failure mode as the cert
                // mount described above), silently booting nodes with a previous run's config.
                ["volumes"] = BuildVolumeMounts(spec, node, configDirInCompose),
                ["networks"] = new Dictionary<string, object>
                {
                    ["caraxes"] = new Dictionary<string, object> { ["ipv4_address"] = node.Ip },
                },
            };

            // Only a named-volume data mount needs a top-level volume entry; a tmpfs mount does not.
            if (spec.DataTmpfsMb <= 0)
                volumes[node.VolumeName] = new Dictionary<string, object>();
        }

        Dictionary<string, object> root = new()
        {
            ["name"] = plan.ProjectName,
            ["services"] = services,
            ["volumes"] = volumes,
            ["networks"] = new Dictionary<string, object>
            {
                ["caraxes"] = new Dictionary<string, object>
                {
                    ["driver"] = "bridge",
                    ["ipam"] = new Dictionary<string, object>
                    {
                        ["config"] = new List<object>
                        {
                            new Dictionary<string, object> { ["subnet"] = plan.NetworkSubnetCidr },
                        },
                    },
                },
            },
        };

        StringBuilder sb = new();
        sb.AppendLine($"# Generated by caraxes for cluster '{spec.Name}'. Do not edit.");
        sb.Append(new SerializerBuilder().Build().Serialize(root));
        return sb.ToString();
    }

    /// <summary>
    /// Builds a node's volume mounts. The config directory is always bind-mounted read-only. The data
    /// mount is either a named volume (the default) or, when <c>data_tmpfs_mb</c> is set, a size-capped
    /// tmpfs — the cap is what lets a <c>disk-full</c> fault exhaust free space on demand. A list of
    /// mixed entries (string short-form and mapping long-form) is valid compose.
    /// </summary>
    private static List<object> BuildVolumeMounts(ClusterSpec spec, NodePlan node, string configDirInCompose)
    {
        List<object> mounts = [];

        if (spec.DataTmpfsMb > 0)
        {
            mounts.Add(new Dictionary<string, object>
            {
                ["type"] = "tmpfs",
                ["target"] = "/data",
                ["tmpfs"] = new Dictionary<string, object> { ["size"] = (long)spec.DataTmpfsMb * 1024 * 1024 },
            });
        }
        else
        {
            mounts.Add($"{node.VolumeName}:/data");
        }

        mounts.Add($"{configDirInCompose}:/app/caraxes-config:ro");
        return mounts;
    }
}
