/**
 * This file is part of Caraxes
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

using System.Text;
using YamlDotNet.Serialization;

namespace Caraxes.Core.Cluster;

/// <summary>
/// Generates one CamusDB <c>config.yml</c> per node, mounted read-only over the image's baked
/// <c>/app/Config/config.yml</c>. Node identity (name, id, host, ports, peers) stays in the
/// container's CAMUS_* environment — CLI flags outrank the file — so the file carries only what
/// the spec shapes: transaction defaults, sharding/query knobs, the <c>kahuna:</c> placement and
/// balancer section, and diagnostics. Only the zone differs between nodes.
/// </summary>
public static class NodeConfigGenerator
{
    public static string Generate(ClusterPlan plan, NodePlan node)
    {
        ClusterSpec spec = plan.Spec;

        // Ordered dictionaries keep the emitted file stable so run artifacts diff cleanly.
        Dictionary<string, object> kahuna = new()
        {
            ["replication_factor"] = spec.ReplicationFactor,
            ["enable_placement_rebalancer"] = spec.PlacementRebalancer,
            ["enable_leader_balancer"] = spec.LeaderBalancer,
        };

        if (node.Zone is not null)
            kahuna["zone"] = node.Zone;

        // Spec-level passthrough last, so an explicit kahuna key in the spec wins over the
        // modeled fields if both name the same option.
        foreach ((string key, object value) in spec.Kahuna)
            kahuna[key] = value;

        Dictionary<string, object> root = new()
        {
            ["data_dir"] = "/data/",
            ["default_transaction_locking"] = spec.Locking,
            ["default_isolation_level"] = spec.Isolation,
            ["key_range_sharding"] = spec.KeyRangeSharding,
            ["distributed_query_execution"] = spec.DistributedQueryExecution,
            ["max_query_parallelism"] = spec.MaxQueryParallelism,
            ["kahuna"] = kahuna,
            ["diagnostics"] = new Dictionary<string, object>
            {
                ["enabled"] = spec.Diagnostics,
                ["prometheus_enabled"] = spec.Diagnostics,
            },
        };

        StringBuilder sb = new();
        sb.AppendLine($"# Generated by caraxes for cluster '{spec.Name}', node {node.Name}. Do not edit.");
        sb.Append(new SerializerBuilder().Build().Serialize(root));
        return sb.ToString();
    }
}
